version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'nerdstore'
      RABBITMQ_DEFAULT_PASS: 'nerdstore'

  postgresql-nerdstore:
    image: robertoalves18/nerdstore-postgresql:latest
    volumes:
      - /c/DockerProjecs/postgres/postgres_db:/var/lib/postgresql/data
    container_name: postgresql-nerdstore
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin!

  web-mvc:
    image: robertoalves18/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    mem_limit: 1024m
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5003
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras

  api-identidade:
    image: robertoalves18/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    mem_limit: 256m
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5001;http://+5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql-nerdstore

  api-carrinho:
    image: robertoalves18/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/NSE.Carrinho.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5009;http://+5008
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - postgresql-nerdstore

  api-catalogo:
    image: robertoalves18/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5005;http://+5004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql-nerdstore

  api-cliente:
    image: robertoalves18/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./services/NSE.Cliente.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5007;http://+5006
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - postgresql-nerdstore

  api-bff-compras:
    image: robertoalves18/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5011;http://+5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido

  api-pagamento:
    image: robertoalves18/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./services/NSE.Pagamento.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5015;http://+5014
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - api-pedido
      - postgresql-nerdstore

  api-pedido:
    image: robertoalves18/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./services/NSE.Pedido.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5013;http://+5012
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - postgresql-nerdstore

  nerdstore-server:
    image: robertoalves18/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web-mvc
