version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: 'nerdstore'
      RABBITMQ_DEFAULT_PASS: 'nerdstore'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgresql-nerdstore:
    image: postgres
    volumes:
      - //c/volumes-docker/nerdstore:/var/lib/postgresql
    container_name: postgres-nerdstore-c
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin!

  web-mvc:
    image: robertoalves18/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports:
      - '5003:5003'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5003
    depends_on:
      - api-catalogo
      - api-identidade
      - api-carrinho

  api-identidade:
    image: robertoalves18/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql-nerdstore

  api-catalogo:
    image: robertoalves18/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5005
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql-nerdstore

  api-carrinho:
    image: robertoalves18/nerdstore-api-carrinho
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/NSE.Carrinho.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5009
    restart: on-failure
    depends_on:
      - rabbitmq
      - api-identidade
      - postgresql-nerdstore
